export const SET_USER = 'SET_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const SET_JOB_TO_BE_UPDATED = 'SET_JOB_TO_BE_UPDATED';
export const SET_ARTICLE_TO_BE_UPDATED = 'SET_ARTICLE_TO_BE_UPDATED';

export const HANDLE_UPDATE_JOB_INPUT = 'HANDLE_UPDATE_JOB_INPUT';